import type { AIModel, Plan } from "@/types";

export const APP_NAME = "Sad";
export const APP_TAGLINE = "One workspace. Every capability.";
export const APP_DESCRIPTION = "Sad brings intelligence, research, creation, coding, analysis and automation into one beautifully designed AI workspace.";

export const NEXA_MODELS: AIModel[] = [
  {
    id: "nexa-fast",
    name: "Sad Fast",
    description: "Fast everyday conversations",
    provider: "default",
    category: "fast",
    icon: "⚡",
    maxTokens: 8192,
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    isDefault: true,
  },
  {
    id: "nexa-pro",
    name: "Sad Pro",
    description: "Advanced reasoning and analysis",
    provider: "default",
    category: "pro",
    icon: "✦",
    maxTokens: 32768,
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
  },
  {
    id: "nexa-vision",
    name: "Sad Vision",
    description: "Multimodal image and video analysis",
    provider: "default",
    category: "vision",
    icon: "👁",
    maxTokens: 16384,
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: false,
  },
  {
    id: "nexa-research",
    name: "Sad Research",
    description: "Deep research and web intelligence",
    provider: "default",
    category: "research",
    icon: "🔬",
    maxTokens: 65536,
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
  },
  {
    id: "nexa-code",
    name: "Sad Code",
    description: "Software engineering and debugging",
    provider: "default",
    category: "code",
    icon: "⌨",
    maxTokens: 32768,
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
  },
  {
    id: "nexa-creative",
    name: "Sad Creative",
    description: "Writing, brainstorming, and creative tasks",
    provider: "default",
    category: "creative",
    icon: "🎨",
    maxTokens: 16384,
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: false,
  },
];

export const PLANS: Plan[] = [
  {
    id: "free",
    name: "Free",
    description: "Get started with basic AI access",
    price: 0,
    interval: "monthly",
    features: [
      "50 messages per day",
      "Nexa Fast model",
      "Basic file analysis",
      "2 GB storage",
      "3 projects",
      "Community support",
    ],
    limits: {
      messagesPerDay: 50,
      storageGB: 2,
      researchPerMonth: 5,
      imageGenPerMonth: 10,
      maxProjects: 3,
      maxAssistants: 1,
    },
  },
  {
    id: "plus",
    name: "Plus",
    description: "Higher limits and advanced capabilities",
    price: 20,
    interval: "monthly",
    features: [
      "500 messages per day",
      "Nexa Fast & Pro models",
      "File & image analysis",
      "10 GB storage",
      "10 projects",
      "10 research per month",
      "50 image generations",
      "Priority support",
    ],
    limits: {
      messagesPerDay: 500,
      storageGB: 10,
      researchPerMonth: 10,
      imageGenPerMonth: 50,
      maxProjects: 10,
      maxAssistants: 5,
    },
    isPopular: true,
  },
  {
    id: "pro",
    name: "Pro",
    description: "Advanced reasoning, research, and tools",
    price: 50,
    interval: "monthly",
    features: [
      "Unlimited messages",
      "All Nexa models",
      "Deep Research",
      "Advanced data analysis",
      "50 GB storage",
      "Unlimited projects",
      "50 research per month",
      "200 image generations",
      "Custom assistants",
      "Automations",
      "Priority support",
    ],
    limits: {
      messagesPerDay: 5000,
      storageGB: 50,
      researchPerMonth: 50,
      imageGenPerMonth: 200,
      maxProjects: 100,
      maxAssistants: 25,
    },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Teams, SSO, audit logs, and enterprise controls",
    price: 0,
    interval: "monthly",
    features: [
      "Everything in Pro",
      "SSO / SAML",
      "Admin dashboard",
      "Audit logs",
      "Custom model deployment",
      "Dedicated support",
      "Custom data retention",
      "API access",
      "SLA guarantee",
    ],
    limits: {
      messagesPerDay: 99999,
      storageGB: 500,
      researchPerMonth: 500,
      imageGenPerMonth: 1000,
      maxProjects: 9999,
      maxAssistants: 9999,
    },
  },
];

export const NAV_ITEMS = [
  { id: "home", label: "Home", icon: "Home", href: "/app" },
  { id: "chats", label: "Chats", icon: "MessageSquare", href: "/app/chats" },
  { id: "projects", label: "Projects", icon: "FolderKanban", href: "/app/projects" },
  { id: "research", label: "Research", icon: "Microscope", href: "/app/research" },
  { id: "library", label: "Library", icon: "Library", href: "/app/library" },
  { id: "assistants", label: "Assistants", icon: "Bot", href: "/app/assistants" },
  { id: "automations", label: "Automations", icon: "Zap", href: "/app/automations" },
  { id: "discover", label: "Discover", icon: "Compass", href: "/app/discover" },
] as const;

export const QUICK_ACTIONS = [
  { id: "research", label: "Deep Research", description: "Get in-depth answers with verified sources", icon: "Microscope", color: "from-violet-500/10 to-indigo-500/10 text-violet-600 dark:text-violet-400" },
  { id: "analyze", label: "Analyze Anything", description: "Upload files, images, code, or data", icon: "ScanSearch", color: "from-cyan-500/10 to-blue-500/10 text-cyan-600 dark:text-cyan-400" },
  { id: "image", label: "Create Images", description: "Generate stunning images with AI", icon: "Image", color: "from-pink-500/10 to-rose-500/10 text-pink-600 dark:text-pink-400" },
  { id: "code", label: "Code with Nexa", description: "Write, debug, and improve code", icon: "Code2", color: "from-emerald-500/10 to-green-500/10 text-emerald-600 dark:text-emerald-400" },
  { id: "assistants", label: "Your Assistants", description: "Create custom AI assistants", icon: "Bot", color: "from-amber-500/10 to-orange-500/10 text-amber-600 dark:text-amber-400" },
] as const;
